spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    # TUNING: Production Grade (High Concurrency)
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # --- ADD THIS (Strict Validation for Prod) ---
  jpa:
    hibernate:
      ddl-auto: validate # CRITICAL: Fails if schema doesn't match, doesn't modify DB.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # ---------------------------------------------

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: transaction-group-prod
      auto-offset-reset: latest

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

logging:
  level:
    root: ERROR
    com.example.fintech: INFO